### ISSUE TITLE
Broken on Node upgrade to v0.12.7

### ISSUE THREAD

**Issue by binarymist** [freewil/express-form#21]
"express-form": "^0.12.4"

I Had validation and sanitisation working fine until I upgraded Node. Now I'm getting:

TypeError: undefined is not a function
    at form.field (myapp/node_modules/express-form/lib/form.js:30:23)
    at callbacks (myapp/node_modules/express/lib/router/index.js:161:37)
    at param (myapp/node_modules/express/lib/router/index.js:135:11)
    at pass (myapp/node_modules/express/lib/router/index.js:142:5)
    at Router._dispatch (myapp/node_modules/express/lib/router/index.js:170:5)
    at Object.router (myapp/node_modules/express/lib/router/index.js:33:10)
    at next (myapp/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.logger (myapp/node_modules/express/node_modules/connect/lib/middleware/logger.js:156:5)
    at next (myapp/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.methodOverride [as handle] (myapp/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:37:5)

So hasOwnProperty is not a method of req.body on line 30 of form.js

So far if I comment out line https://github.com/freewil/express-form/blob/master/lib/form.js#L30 Then I don't get any further issues. Not really sure what that lines for.

Thanks.

**Comment by freewil** [comment]
You need to add `body-parser` before using `express-form` in the middleware stack, otherwise `req.body` will be undefined. Refer to the first example in the readme.

**Comment by binarymist** [comment]
Strangely looking at my commits, it looks like I did. I've just upgraded to express 4 and I don't have any issues at this stage.

Thanks for the heads up, oh and for saving me a lot of time with the module.
